### ISSUE TITLE
[question] Il corso su youtube continuera'?

### ISSUE THREAD

**Issue by Plaoo** [harisont/imparalhaskell#1]
Ciao, da poco ho visto che hai iniziato un videocorso su youtube riguardante Haskell, vorrei iniziarlo ma ho notato che il tuo ultimo video risale a qualche mese fa. Volevo chiederti se e' finito (non credo), oppure l'hai stoppato per x motivi.
Grazie, comunque spero che possa continuare.

**Comment by harisont** [comment]
Ciao!
Sono felice che tu ti stia interessando al videocorso.
In effetti ho dovuto mettere in pausa il corso per molto più tempo di quanto non avessi inizialmente pensato, **ma** sto riprendendo in mano il progetto proprio in questi giorni e pervedo di caricare il prossimo episodio nel corso delle prossime due settimane. 

Inoltre ho l'obiettivo (ma non posso promettere) di completare il corso base entro la fine dell'anno.

Ci vediamo su YouTube!
